spring:
  application:
    name: shoe-moa
  profiles:
    active: prod   # 기본 실행 프로파일
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
#        use_sql_comments: true

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      region:
        static: ${AWS_REGION}
      s3:
        bucket: ${AWS_S3_BUCKET}
      stack:
        auto: false  # CloudFormation 비활성화

cloudfront:
  domain: d3to55zvtt5gof.cloudfront.net

logging:
  level:
#    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  override-with-generic-response: false
  show-actuator: false

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000  # 1시간 (밀리초 단위)


app:
  admin:
    initial-password: ${ADMIN_PW}
  cors:
    allowed-origins: http://localhost:3000


