spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shoemoa
    driver-class-name: org.postgresql.Driver
    username: shoemoa
    password: shoemoa

  jpa:
    hibernate:
      ddl-auto: create   # ❗ 운영에서는 절대 create/update 금지
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
