spring:
  application:
    name: shoe-moa


  profiles:
    active: prod   # 기본 실행 프로파일

  jpa:
    open-in-view: false   # ❗ 무조건 끄기 (CORE.md 스타일에 필수)
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
#        use_sql_comments: true

logging:
  level:
#    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
